/**
 * Generates supabase/seed.sql from the same demonstration data used by local demo mode
 * (src/lib/data/seed.ts), so both modes show identical content.
 *   npx tsx scripts/generate-seed-sql.ts
 */
import { writeFileSync } from "node:fs";
import { buildSeed, DEMO_PASSWORD } from "../src/lib/data/seed";

const db = buildSeed();
const idMap = new Map<string, string>();
let counter = 0;
const uuid = (id: string | null) => {
  if (!id) return null;
  if (!idMap.has(id)) {
    counter++;
    const prefix = id.startsWith("u_") ? "0000aaaa" : id.startsWith("job_") ? "0000bbbb" : "0000cccc";
    idMap.set(id, `${prefix}-0000-4000-8000-${counter.toString().padStart(12, "0")}`);
  }
  return idMap.get(id)!;
};

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  if (Array.isArray(v)) return v.length ? `array[${v.map(q).join(",")}]` : "'{}'";
  if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const qArr = (v: string[], type = "text") => (v.length ? `array[${v.map(q).join(",")}]::${type}[]` : `'{}'::${type}[]`);

const out: string[] = [];
out.push(`-- =====================================================================
-- TaskTeens DEMONSTRATION SEED DATA — generated by scripts/generate-seed-sql.ts
-- All people, employers and listings are fictional (jobs.is_demo = true).
-- Demo password for every account: ${DEMO_PASSWORD}
-- DO NOT run against a production project with real users.
-- =====================================================================
begin;
`);

out.push("-- reference data");
for (const c of db.categories)
  out.push(`insert into public.categories (slug,name,description,icon,active,sort) values (${q(c.slug)},${q(c.name)},${q(c.description)},${q(c.icon)},${q(c.active)},${c.sort}) on conflict (slug) do update set name=excluded.name, description=excluded.description, icon=excluded.icon, sort=excluded.sort;`);
for (const a of db.service_areas)
  out.push(`insert into public.service_areas (slug,name,cities,active) values (${q(a.slug)},${q(a.name)},${qArr(a.cities)},${q(a.active)}) on conflict (slug) do update set name=excluded.name, cities=excluded.cities;`);

out.push("\n-- auth users (trigger public.handle_new_user creates public.users + teen_profiles)");
for (const u of db.users) {
  const id = uuid(u.id);
  const signupRole = u.role === "admin" ? "teen" : u.role; // admin is promoted below, never via metadata
  out.push(`insert into auth.users (instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,recovery_token,email_change_token_new,email_change)
values ('00000000-0000-0000-0000-000000000000',${q(id)},'authenticated','authenticated',${q(u.email)},crypt(${q(DEMO_PASSWORD)}, gen_salt('bf')),now(),'{"provider":"email","providers":["email"]}'::jsonb,${q({ full_name: u.full_name, role: signupRole })},${q(u.created_at)},now(),'','','','') on conflict (id) do nothing;`);
  out.push(`insert into auth.identities (id,user_id,provider_id,identity_data,provider,last_sign_in_at,created_at,updated_at)
values (gen_random_uuid(),${q(id)},${q(id)},${q({ sub: id, email: u.email, email_verified: true })},'email',now(),now(),now()) on conflict do nothing;`);
}
out.push(`update public.users set role = 'admin' where id = ${q(uuid("u_admin"))};`);
for (const u of db.users) if (u.phone) out.push(`update public.users set phone = ${q(u.phone)} where id = ${q(uuid(u.id))};`);

out.push("\n-- teen profiles");
for (const t of db.teen_profiles)
  out.push(`update public.teen_profiles set display_name=${q(t.display_name)}, age_range=${q(t.age_range)}, city=${q(t.city)}, bio=${q(t.bio)}, skills=${qArr(t.skills)}, experience=${q(t.experience)}, availability=${q(t.availability)}, transportation=${q(t.transportation)}, portfolio_url=${q(t.portfolio_url)}, work_permit_status=${q(t.work_permit_status)}, guardian_consent_status=${q(t.guardian_consent_status)} where user_id=${q(uuid(t.user_id))};`);

out.push("\n-- employer profiles");
for (const e of db.employer_profiles)
  out.push(`insert into public.employer_profiles (user_id,employer_type,display_name,city,service_area,website,description,verification_status,agreed_to_rules_at,onboarded) values (${q(uuid(e.user_id))},${q(e.employer_type)},${q(e.display_name)},${q(e.city)},${q(e.service_area)},${q(e.website)},${q(e.description)},${q(e.verification_status)},now(),true) on conflict (user_id) do nothing;`);

out.push("\n-- jobs (demo listings)");
for (const j of db.jobs)
  out.push(`insert into public.jobs (id,employer_id,title,category,description,responsibilities,required_skills,preferred_skills,city,neighborhood,service_area,work_mode,pay_type,pay_min,pay_max,schedule,schedule_tags,min_age,start_date,recurrence,openings,deadline,transportation,transportation_notes,image_url,status,moderation_status,featured,is_demo,created_at,published_at) values (${q(uuid(j.id))},${q(uuid(j.employer_id))},${q(j.title)},${q(j.category)},${q(j.description)},${qArr(j.responsibilities)},${qArr(j.required_skills)},${qArr(j.preferred_skills)},${q(j.city)},${q(j.neighborhood)},${q(j.service_area)},${q(j.work_mode)},${q(j.pay_type)},${j.pay_min},${q(j.pay_max)},${q(j.schedule)},${qArr(j.schedule_tags)},${j.min_age},(current_date + ${Math.round((new Date(j.start_date ?? Date.now()).getTime() - Date.now()) / 86400000)}),${q(j.recurrence)},${j.openings},(current_date + ${Math.round((new Date(j.deadline ?? Date.now()).getTime() - Date.now()) / 86400000)}),${q(j.transportation)},${q(j.transportation_notes)},${q(j.image_url)},${q(j.status)},${q(j.moderation_status)},${q(j.featured)},true,${q(j.created_at)},${q(j.published_at)}) on conflict (id) do nothing;`);

out.push("\n-- applications (triggers create the matching notifications)");
for (const a of db.applications)
  out.push(`insert into public.applications (id,job_id,employer_id,teen_id,status,applicant_name,applicant_email,applicant_phone,age_range,city,experience,skills,availability,transportation,interest_statement,portfolio_url,work_permit_status,guardian_consent_status,agreed_to_safety_rules,viewed_at,status_updated_at,created_at) values (${q(uuid(a.id))},${q(uuid(a.job_id))},${q(uuid(a.employer_id))},${q(uuid(a.teen_id))},${q(a.status)},${q(a.applicant_name)},${q(a.applicant_email)},${q(a.applicant_phone)},${q(a.age_range)},${q(a.city)},${q(a.experience)},${qArr(a.skills)},${q(a.availability)},${q(a.transportation)},${q(a.interest_statement)},${q(a.portfolio_url)},${q(a.work_permit_status)},${q(a.guardian_consent_status)},true,${q(a.viewed_at)},${q(a.status_updated_at)},${q(a.created_at)}) on conflict do nothing;`);

for (const n of db.application_notes)
  out.push(`insert into public.application_notes (application_id,employer_id,body) values (${q(uuid(n.application_id))},${q(uuid(n.employer_id))},${q(n.body)});`);

for (const i of db.interview_requests)
  out.push(`insert into public.interview_requests (application_id,job_id,employer_id,teen_id,proposed_times,format,location_note,message,guardian_invited,status) values (${q(uuid(i.application_id))},${q(uuid(i.job_id))},${q(uuid(i.employer_id))},${q(uuid(i.teen_id))},array[${i.proposed_times.map((t) => `(now() + interval '${Math.max(1, Math.round((new Date(t).getTime() - Date.now()) / 3600000))} hours')`).join(",")}]::timestamptz[],${q(i.format)},${q(i.location_note)},${q(i.message)},${q(i.guardian_invited)},${q(i.status)});`);

for (const s of db.saved_jobs) out.push(`insert into public.saved_jobs (user_id,job_id) values (${q(uuid(s.user_id))},${q(uuid(s.job_id))}) on conflict do nothing;`);

for (const v of db.verification_requests)
  out.push(`insert into public.verification_requests (employer_id,employer_type,submitted_info,status,reviewer_id,review_note,reviewed_at) values (${q(uuid(v.employer_id))},${q(v.employer_type)},${q(v.submitted_info)},${q(v.status)},${q(uuid(v.reviewer_id))},${q(v.review_note)},${q(v.reviewed_at)});`);

for (const r of db.reports)
  out.push(`insert into public.reports (reporter_id,target_type,target_id,reason,details,severity,status) values (${q(uuid(r.reporter_id))},${q(r.target_type)},${q(r.target_id ? uuid(r.target_id) : null)},${q(r.reason)},${q(r.details)},${q(r.severity)},${q(r.status)});`);

for (const l of db.admin_audit_logs)
  out.push(`insert into public.admin_audit_logs (admin_id,action,target_type,target_id,note,created_at) values (${q(uuid(l.admin_id))},${q(l.action)},${q(l.target_type)},${q(uuid(l.target_id))},${q(l.note)},${q(l.created_at)});`);

out.push("\ncommit;\n");
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n"));
console.log(`Wrote supabase/seed.sql (${out.length} statements)`);
